---
output: pdf_document
header-includes:
  - \pagenumbering{gobble}
  - \usepackage{multicol}
  - \usepackage{graphicx}
  - \usepackage{longtable}
  - \graphicspath{ {.} }
geometry: margin = 0.25in
date: "`r Sys.Date()`"
params:
  report_header: report_header
  combined_plot: combined_plot
  pitch_split: pitch_split
---

```{r echo=FALSE, message=FALSE}
# cat("DEBUG: params$report_header =\n")
# str(params$report_header)

# Create header strings safely
header_name <- tryCatch(
  paste0(params$report_header[["name"]], " Pitching"),
  error = function(e) "Unknown Player"
)

header_date <- tryCatch(
  paste0(params$report_header[["date1"]], " to ", params$report_header[["date2"]]),
  error = function(e) "Unknown Date Range"
)
```

\begin{multicols}{2}
\large\textbf{`r header_name`}
\columnbreak
\large\textbf{`r header_date`}
\end{multicols}

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=9, fig.height=4}
params$combined_plot
```

```{r echo=FALSE, fig.height=2, fig.width=9, message=FALSE, warning=FALSE}
knitr::kable(params$pitch_split, format="markdown", longtable = TRUE, caption = "Pitch Split Overview")
```

